apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teslaboard-cert
spec:
  secretName: teslaboard-cert-tls
  commonName: teslaboard.local
  dnsNames:
    - teslaboard.local
    - teslaboard.internal
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - rpi5
    provinces:
      - California
    countries:
      - US
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: anshulg-ca
