apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  replicas: 3
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      name: miniflux
      labels:
        app: miniflux
    spec:
      containers:
        - name: miniflux
          image: ghcr.io/miniflux/miniflux:2.2.4@sha256:20adbf84f0d8cd24b4ebbc138e31087419a274fd9c717c6a909b0773b4538b98
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              protocol: TCP
          env:
            - name: GOMAXPROCS
              valueFrom:
                resourceFieldRef:
                  divisor: '1'
                  resource: limits.cpu
            - name: GOMEMLIMIT
              valueFrom:
                resourceFieldRef:
                  divisor: '1'
                  resource: limits.memory
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  key: uri
                  name: miniflux-cluster-app
            # - name: RUN_MIGRATIONS
            #   value: "1"
            # - name: CREATE_ADMIN
            #   value: "1"
            - name: ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  key: adminUsername
                  name: miniflux-secret
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: adminPassword
                  name: miniflux-secret
            - name: BASE_URL
              value: "https://miniflux.anshulg.com/"
            - name: FETCH_YOUTUBE_WATCH_TIME
              value: "1"
            - name: WEBAUTHN
              value: "0"
            - name: LOG_FORMAT
              value: "json"
            - name: CLEANUP_ARCHIVE_READ_DAYS
              value: "-1"
            - name: CLEANUP_ARCHIVE_UNREAD_DAYS
              value: "-1"
            - name: SERVER_TIMING_HEADER
              value: "1"
            - name: HTTP_CLIENT_PROXY
              valueFrom:
                secretKeyRef:
                  key: proxyUrl
                  name: miniflux-secret
            - name: OAUTH2_PROVIDER
              value: oidc
            - name: OAUTH2_CLIENT_ID
              value: "miniflux"
            - name: OAUTH2_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  key: oauthClientSecret
                  name: miniflux-secret
            - name: OAUTH2_REDIRECT_URL
              value: "https://miniflux.anshulg.com/oauth2/oidc/callback"
            - name: OAUTH2_OIDC_DISCOVERY_ENDPOINT
              value: "https://auth.anshulg.com/oauth2/openid/miniflux"
            - name: OAUTH2_USER_CREATION
              value: "1"
          resources:
            requests:
              cpu: 25m
              memory: 64Mi
            limits:
              memory: 128Mi
          readinessProbe:
            httpGet:
              port: 8080
              path: /healthcheck
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            exec:
              command:
                - /usr/bin/miniflux
                - -healthcheck
                - auto
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: miniflux
