apiVersion: batch/v1
kind: CronJob
metadata:
  name: pp-tree-importer
spec:
  schedule: "*/15 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: pp-tree-importer
              image: ghcr.io/ansg191-lab/pp-tree-importer2:main@sha256:67612d93ee6942ff8b4e004e39b420c63a9b1a754be551492d8272c17604b9be
              imagePullPolicy: IfNotPresent
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/secret/credentials.json"
                - name: RUST_LOG
                  value: "info"
                - name: PP_GDRIVE_FOLDER
                  value: "1TDAKn_ud7ofTVnSQl-mjB92c3JqFvQWF"
                - name: PP_BUCKET
                  value: "pp-trees-images"
                - name: PP_LOG_FORMAT
                  value: "json"
                - name: RUST_BACKTRACE
                  value: "1"
              volumeMounts:
                - mountPath: /secret
                  name: secret
              resources:
                requests:
                  cpu: 500m
                  memory: 1Gi
                limits:
                  memory: 1536Mi
          volumes:
            - name: secret
              secret:
                secretName: pptree-secrets
          restartPolicy: OnFailure
