apiVersion: v1
kind: Namespace
metadata:
  name: ddog
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ddog
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: datadog
    repoURL: https://helm.datadoghq.com
    targetRevision: 3.84.0
    helm:
      values: |
        datadog:
          apiKeyExistingSecret: ddog-api-key
          logs:
            enabled: true
            containerCollectAll: true
          networkMonitoring:
            enabled: true
          apm:
            portEnabled: true
          otlp:
            receiver:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                  enabled: true
                http:
                  endpoint: 0.0.0.0:4318
                  enabled: true
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: ddog
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
