apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: Miniflux
  sourceRepos:
    - {{ .Values.spec.source.repoURL }}
    - https://charts.bitnami.com/bitnami
  destinations:
    - namespace: miniflux
      server: {{ .Values.spec.destination.server }}
    - namespace: argocd
      server: {{ .Values.spec.destination.server }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: miniflux
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miniflux
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: miniflux
  project: miniflux
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: k8s/miniflux
