apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rss-bridge-cert
spec:
  secretName: rss-bridge-cert-tls
  commonName: rss-bridge.anshulg.com
  dnsNames:
    - rss-bridge.anshulg.com
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - k8s
    provinces:
      - California
    countries:
      - US
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: anshulg-ca
