apiVersion: apps/v1
kind: Deployment
metadata:
  name: n-eight-n
  labels:
    app: n8n
spec:
  selector:
    matchLabels:
      app: n8n
  replicas: 1
  template:
    metadata:
      labels:
        app: n8n
    spec:
      containers:
        - name: n-eight-n
          image: n8nio/n8n:1.78.0@sha256:762ba5de53262c257d14aa875b565c4ade9f870fef4dab36bb79951f0ae06b87
          ports:
            - containerPort: 5678
          volumeMounts:
            - mountPath: /root/.n8n
              name: n8n-data
          env:
            - name: WEBHOOK_URL
              value: https://n8n.anshulg.com/
            - name: GENERIC_TIMEZONE
              value: America/Los_Angeles
          securityContext:
            allowPrivilegeEscalation: false
            runAsUser: 0
            runAsGroup: 0
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-claim
