apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-ca-deployment
  labels:
    app.kubernetes.io/name: nginx-ca-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: nginx-ca-deployment
  template:
    metadata:
      labels:
        app.kubernetes.io/name: nginx-ca-deployment
    spec:
      containers:
        - name: nginx
          image: nginx:1.27.3@sha256:bc2f6a7c8ddbccf55bdb19659ce3b0a92ca6559e86d42677a5a02ef6bda2fcef
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: /usr/share/nginx/html
              name: ca-crt
            - mountPath: /etc/nginx
              name: nginx-conf
      volumes:
        - name: ca-crt
          configMap:
            name: anshulg-cert
        - name: nginx-conf
          configMap:
            name: nginx-conf
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |-
    user nginx;
    worker_processes auto;
    error_log /var/log/nginx/error.log;
    events {
      worker_connections 10240;
    }
    http {
      log_format main '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';
      access_log /var/log/nginx/access.log main;
      sendfile on;
      tcp_nopush on;
      tcp_nodelay on;
      keepalive_timeout 65;
      types_hash_max_size 2048;
      # include /etc/nginx/mime.types;
      default_type application/octet-stream;
      # include /etc/nginx/conf.d/*.conf;
      server {
        listen 80;
        server_name _;
        location / {
          root /usr/share/nginx/html;
          index ca.crt;
        }
      }
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anshulg-cert
data:
  ca.crt: |-
    -----BEGIN CERTIFICATE-----
    MIICkTCCAhegAwIBAgITRe+W6sTxr58PnbCucZrDWaYZ8jAKBggqhkjOPQQDAzBY
    MQswCQYDVQQGEwJVUzETMBEGA1UECBMKQ2FsaWZvcm5pYTEVMBMGA1UEChMMQW5z
    aHVsIEd1cHRhMR0wGwYDVQQDExRBbnNodWwgR3VwdGEgUm9vdCBDQTAeFw0yMzA4
    MDgwODI2MTJaFw0zMzA4MDUwODI2MTFaMFgxCzAJBgNVBAYTAlVTMRMwEQYDVQQI
    EwpDYWxpZm9ybmlhMRUwEwYDVQQKEwxBbnNodWwgR3VwdGExHTAbBgNVBAMTFEFu
    c2h1bCBHdXB0YSBSb290IENBMHYwEAYHKoZIzj0CAQYFK4EEACIDYgAElYXQLHg0
    WNyvq46Itf45IVd966Q6du/W33j16wMrZSke8MTOPei2Xb8WwVQeudzuWMV5Dvyx
    5y+8+4ONMBHVDZmc3d9KVkLMmA8PL5IzjPR6EO8X1slmg760WXpAViEDo4GiMIGf
    MA8GA1UdDwEB/wQFAwMH/oAwOwYDVR0lBDQwMgYIKwYBBQUHAwEGCCsGAQUFBwMC
    BggrBgEFBQcDAwYIKwYBBQUHAwQGCCsGAQUFBwMIMA8GA1UdEwEB/wQFMAMBAf8w
    HQYDVR0OBBYEFB9QT00cjwfCTDAEFnF0bTCm5/dNMB8GA1UdIwQYMBaAFB9QT00c
    jwfCTDAEFnF0bTCm5/dNMAoGCCqGSM49BAMDA2gAMGUCMBUIC2YkVYFZQ8eO5gpr
    r4pNG8au2uGUwU1JQP2lIa3hcgoXDyESUfmO4VG6MvEUxQIxANQxgJ4ynOGBCXIL
    LkSEwEOKuv4iyDxh7kzrgPb0EaBq9+VCIwrCVoXtQIxq9hBU8g==
    -----END CERTIFICATE-----
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-ca-service
spec:
  selector:
    app.kubernetes.io/name: nginx-ca-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
---
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: nginx-ca
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`ca.anshulg.com`)
      services:
        - name: nginx-ca-service
          port: 80
  tls:
    secretName: ca-anshulg-com-tls
    domains:
      - main: ca.anshulg.com
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: ca-anshulg-com-tls
spec:
  secretName: ca-anshulg-com-tls
  commonName: ca.anshulg.com
  dnsNames:
    - ca.anshulg.com
  duration: 2160h0m0s
  privateKey:
    algorithm: ECDSA
    size: 256
    rotationPolicy: Always
  issuerRef:
    name: anshulg-ca
    kind: GoogleCASClusterIssuer
    group: cas-issuer.jetstack.io
