apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: radarr
  annotations:
    external-dns.alpha.kubernetes.io/target: 192.168.1.100
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: Host(`radarr.local`) || Host(`radarr.internal`)
      middlewares:
        - name: security-headers
          namespace: kube-system
      services:
        - name: radarr-auth
          port: 80
  tls:
    secretName: radarr-cert-tls
    domains:
      - main: radarr.local
        sans:
          - radarr.internal
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: radarr
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: radarr
      port:
        number: 80
  tls:
    - hosts:
        - radarr
